import { Content } from "../domain/Content";
import { ContentRepository } from "../domain/ContentRepository";

export class GenerateContent {
    constructor(private readonly repository: ContentRepository) { }

    // Mock implementation of AI generation
    async execute(topic: string, type: Content['type']): Promise<Content> {
        const slug = topic.toLowerCase().replace(/\s+/g, '-');

        // Simulate AI delay
        // In real app, call OpenAI/Gemini here

        const newContent: Content = {
            id: crypto.randomUUID(),
            slug,
            title: `AI Generated Guide: ${topic}`,
            body: `This is a comprehensive guide about **${topic}**. It was generated by our advanced AI engine to boost SEO and provide value to clients.`,
            type,
            tags: ['ai-generated', type, topic],
            seoDescription: `Learn everything about ${topic} in this detailed guide.`,
            createdAt: new Date(),
            updatedAt: new Date(),
        };

        await this.repository.save(newContent);
        return newContent;
    }
}
