import { LegalDocument } from "../domain/LegalDocument";
import { TransactionPreset } from "../domain/TransactionPreset";
import { LegalDocumentRepository } from "../domain/LegalDocumentRepository";
import { TransactionPresetRepository } from "../domain/TransactionPresetRepository";

/**
 * SmartPresetLearner analyzes recent historical documents to extract recurring
 * field patterns and saves them as a TransactionPreset for the user.
 */
export class SmartPresetLearner {
    constructor(
        private readonly documentRepo: LegalDocumentRepository,
        private readonly presetRepo: TransactionPresetRepository
    ) { }

    /**
     * thresholdCount: minimum number of times a specific value must appear 
     * in the document history to be considered a "learned preset"
     */
    async learn(userId: string, documentType: string, historyLimit = 5, thresholdCount = 2): Promise<void> {
        // Find recent generated/signed documents of the same type
        // The implementation assumes the repo has a way to filter or we pull all and filter
        // For efficiency, a real system needs an indexed query. Here we fetch all (mock-friendly) or use a specialized query.
        const allDocs = await this.documentRepo.findAll();

        // In a real scenario, documents belong to brokers/users. 
        // For MVP, we assume global pool or filter by some property owner.
        const recentDocs = allDocs
            .filter((d: LegalDocument) => d.type === documentType && (d.status === 'generated' || d.status === 'signed'))
            .sort((a: LegalDocument, b: LegalDocument) => b.createdAt.getTime() - a.createdAt.getTime())
            .slice(0, historyLimit);

        if (recentDocs.length < thresholdCount) {
            return; // Not enough history to learn anything
        }

        // Count value frequencies across fields
        const valueFrequencies: Record<string, Record<string, number>> = {};

        for (const doc of recentDocs) {
            for (const [key, value] of Object.entries(doc.data)) {
                // Ignore empty or highly dynamic fields (dates, addresses, signatures)
                if (value === null || value === undefined || value === '') continue;
                if (key.includes('date') || key.includes('signature') || key.includes('name')) continue;

                // Treat boolean/string the same for learning
                const strValue = String(value);

                if (!valueFrequencies[key]) {
                    valueFrequencies[key] = {};
                }
                valueFrequencies[key][strValue] = (valueFrequencies[key][strValue] || 0) + 1;
            }
        }

        // Extract values that meet the threshold
        const learnedData: Record<string, unknown> = {};
        for (const [key, freqs] of Object.entries(valueFrequencies)) {
            for (const [strValue, count] of Object.entries(freqs)) {
                if (count >= thresholdCount) {
                    // Try to restore original type (boolean vs string)
                    let finalVal: unknown = strValue;
                    if (strValue === 'true') finalVal = true;
                    if (strValue === 'false') finalVal = false;

                    learnedData[key] = finalVal;
                    break; // Only take the most frequent one that passes threshold
                }
            }
        }

        if (Object.keys(learnedData).length === 0) {
            return; // Nothing new to learn
        }

        // Find existing preset or create new one
        const presetName = `AI Auto-Learned: ${documentType}`;
        const existingPresets = await this.presetRepo.findAll();
        const existing = existingPresets.find((p: TransactionPreset) => p.name === presetName && p.userId === userId);

        if (existing) {
            // Merge with existing so we don't lose manual overrides, but update learned patterns
            const merged = { ...existing.defaultData, ...learnedData };
            existing.update(presetName, merged, "Auto-updated by AI from recent documents");
            await this.presetRepo.save(existing);
        } else {
            const preset = TransactionPreset.create(
                userId,
                presetName,
                learnedData,
                "Auto-generated by AI from recent documents"
            );
            await this.presetRepo.save(preset);
        }
    }
}
